

module.exports.viewAll = function(req, res, next) {
    const cards = [{
        name: 'Bulbasaur',
        hp: 70,
        type: 'grass',
        typeimg: 'https://archives.bulbagarden.net/media/upload/thumb/2/2e/Grass-attack.png/25px-Grass-attack.png',
        image: 'https://archives.bulbagarden.net/media/upload/f/fb/0001Bulbasaur.png',
        atk1nm: 'Tackle',
        atk1en: 1,
        atk1base: 0,
        dmg1: 20,
        atk2nm: 'Vine Whip',
        atk2en: 2,
        atk2base: 0,
        dmg2: 30,
        weak: 'https://archives.bulbagarden.net/media/upload/thumb/a/ad/Fire-attack.png/20px-Fire-attack.png',
        weakquant: 2,
        resist: '',
        resistquant: 0
    },
    {
        name: 'Snom',
        hp: 70,
        type: 'water',
        typeimg: 'https://archives.bulbagarden.net/media/upload/thumb/1/11/Water-attack.png/25px-Water-attack.png',
        image: 'https://archives.bulbagarden.net/media/upload/8/84/0872Snom.png',
        atk1nm: 'Ram',
        atk1en: 0,
        atk1base: 1,
        dmg1: 10,
        atk2nm: 'Call for Family',
        atk2en: 1,
        atk2base: 1,
        weak: 'https://archives.bulbagarden.net/media/upload/thumb/6/64/Metal-attack.png/25px-Metal-attack.png',
        weakquant: 2,
        resist: '',
        resistquant: 0
    },
    {
        name: 'Eevee',
        hp: 70,
        type: 'colorless',
        typeimg: 'https://archives.bulbagarden.net/media/upload/thumb/1/1d/Colorless-attack.png/20px-Colorless-attack.png',
        image: 'https://archives.bulbagarden.net/media/upload/e/ea/Caf%C3%A9_ReMix_Eevee_Shiny.png',
        atk1nm: 'Tackle',
        atk1en: 0,
        atk1base: 1,
        dmg1: 10,
        atk2nm: 'Lunge',
        dmg2: 30,
        atk2en: 0,
        atk2base: 2,
        weak: '',
        weakquant: 0,
        resist: '',
        resistquant: 0
    },
    {
        name: 'Ponyta (Galrian)',
        hp: 70,
        type: 'psychic',
        typeimg: 'https://archives.bulbagarden.net/media/upload/thumb/e/ef/Psychic-attack.png/25px-Psychic-attack.png',
        image: 'https://archives.bulbagarden.net/media/upload/f/ff/077Ponyta-Galar_2.png',
        atk1nm: 'Flop',
        atk1en: 1,
        atk1base: 1,
        dmg1: 20,
        atk2nm: 'Phy Bolt',
        atk2en: 1,
        atk2base: 0,
        dmg2: 30,
        weak: '',
        weakquant: 0,
        resist: '',
        resistquant: 0
    }]
    res.render('index', {cards});
}